name: Validate Pact History
description: Validate pact history of a chainweb database
inputs:
  chainweb_version:
    description: Chainweb version of the database
    default: 'mainnet01'
runs:
  using: "composite"
  steps:
  - name: Sync chain database from S3
    shell: bash
    run: aws s3 sync "$DB_SNAPSHOT_URI" db/0/rocksDb --delete --exclude=LOCK
    env:
      DB_SNAPSHOT_URI: 's3://chainweb-chain-db/${{ inputs.chainweb_version }}/rocksdb/'
  - name: Write chainweb-node configuration file
    shell: bash
    run: |
      cat >> config.yaml <<EOF
        databaseDirectory: "db"
        chainweb:
          chainwebVersion: ${{ inputs.chainweb_version }}
          validateHashesOnReplay: true
          p2p:
            peer:
              hostaddress:
                hostname: localhost
                port: 4445
            private: true
            ignoreBootstrapNodes: true
          transactionIndex:
            enabled: false
          headerStream: false
          mempoolP2p:
            enabled: false
          cuts:
            pruneChainDatabase: false
        logging:
          telemetryBackend:
            enabled: false
          backend:
            handle: stdout
            color: "True"
          logger:
            log_level: info
            policy: block
          filter:
            rules:
            - key: component
              value: init
              level: info
            default: warn
      EOF
  - name: Validate pact history
    shell: bash
    run: |
      unbuffer chainweb-node --config-file config.yaml |
      { sed -u -e '/finished synchronizing Pact DBs/q0;/\[Error\]/q1;$q2'; x=$?; killall -9 chainweb-node; } ||
      true
      exit $x;
